/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminAgentsRouteImport } from './routes/admin.agents'
import { Route as AdminAppointmentsRouteImport } from './routes/admin.appointments'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminPropertiesRouteImport } from './routes/admin.properties'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AgentChatRouteImport } from './routes/agent.chat'
import { Route as AgentCustomersRouteImport } from './routes/agent.customers'
import { Route as AgentLeadsRouteImport } from './routes/agent.leads'
import { Route as AgentLoginRouteImport } from './routes/agent.login'
import { Route as AgentPropertiesRouteImport } from './routes/agent.properties'
import { Route as AgentSiteVisitsRouteImport } from './routes/agent.site-visits'
import { Route as CustomerAppointmentsRouteImport } from './routes/customer.appointments'
import { Route as CustomerChatRouteImport } from './routes/customer.chat'
import { Route as CustomerEnquiriesRouteImport } from './routes/customer.enquiries'
import { Route as CustomerFavoritesRouteImport } from './routes/customer.favorites'
import { Route as CustomerLoginRouteImport } from './routes/customer.login'
import { Route as CustomerPropertiesRouteImport } from './routes/customer.properties'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin.index'
import { Route as SuperAdminAdminsRouteImport } from './routes/super-admin.admins'
import { Route as SuperAdminLoginRouteImport } from './routes/super-admin.login'
import { Route as SuperAdminSystemReportsRouteImport } from './routes/super-admin.system-reports'
import { Route as SuperAdminUsersRouteImport } from './routes/super-admin.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/admin/agents',
  path: '/admin/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/admin/appointments',
  path: '/admin/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPropertiesRoute = AdminPropertiesRouteImport.update({
  id: '/admin/properties',
  path: '/admin/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentChatRoute = AgentChatRouteImport.update({
  id: '/agent/chat',
  path: '/agent/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentCustomersRoute = AgentCustomersRouteImport.update({
  id: '/agent/customers',
  path: '/agent/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentLeadsRoute = AgentLeadsRouteImport.update({
  id: '/agent/leads',
  path: '/agent/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentLoginRoute = AgentLoginRouteImport.update({
  id: '/agent/login',
  path: '/agent/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentPropertiesRoute = AgentPropertiesRouteImport.update({
  id: '/agent/properties',
  path: '/agent/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentSiteVisitsRoute = AgentSiteVisitsRouteImport.update({
  id: '/agent/site-visits',
  path: '/agent/site-visits',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerAppointmentsRoute = CustomerAppointmentsRouteImport.update({
  id: '/customer/appointments',
  path: '/customer/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerChatRoute = CustomerChatRouteImport.update({
  id: '/customer/chat',
  path: '/customer/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerEnquiriesRoute = CustomerEnquiriesRouteImport.update({
  id: '/customer/enquiries',
  path: '/customer/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerFavoritesRoute = CustomerFavoritesRouteImport.update({
  id: '/customer/favorites',
  path: '/customer/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerLoginRoute = CustomerLoginRouteImport.update({
  id: '/customer/login',
  path: '/customer/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerPropertiesRoute = CustomerPropertiesRouteImport.update({
  id: '/customer/properties',
  path: '/customer/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/super-admin/',
  path: '/super-admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminAdminsRoute = SuperAdminAdminsRouteImport.update({
  id: '/super-admin/admins',
  path: '/super-admin/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminLoginRoute = SuperAdminLoginRouteImport.update({
  id: '/super-admin/login',
  path: '/super-admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminSystemReportsRoute = SuperAdminSystemReportsRouteImport.update({
  id: '/super-admin/system-reports',
  path: '/super-admin/system-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminUsersRoute = SuperAdminUsersRouteImport.update({
  id: '/super-admin/users',
  path: '/super-admin/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/agent/chat': typeof AgentChatRoute
  '/agent/customers': typeof AgentCustomersRoute
  '/agent/leads': typeof AgentLeadsRoute
  '/agent/login': typeof AgentLoginRoute
  '/agent/properties': typeof AgentPropertiesRoute
  '/agent/site-visits': typeof AgentSiteVisitsRoute
  '/customer/appointments': typeof CustomerAppointmentsRoute
  '/customer/chat': typeof CustomerChatRoute
  '/customer/enquiries': typeof CustomerEnquiriesRoute
  '/customer/favorites': typeof CustomerFavoritesRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/properties': typeof CustomerPropertiesRoute
  '/super-admin/admins': typeof SuperAdminAdminsRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/super-admin/system-reports': typeof SuperAdminSystemReportsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/super-admin/': typeof SuperAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/agent/chat': typeof AgentChatRoute
  '/agent/customers': typeof AgentCustomersRoute
  '/agent/leads': typeof AgentLeadsRoute
  '/agent/login': typeof AgentLoginRoute
  '/agent/properties': typeof AgentPropertiesRoute
  '/agent/site-visits': typeof AgentSiteVisitsRoute
  '/customer/appointments': typeof CustomerAppointmentsRoute
  '/customer/chat': typeof CustomerChatRoute
  '/customer/enquiries': typeof CustomerEnquiriesRoute
  '/customer/favorites': typeof CustomerFavoritesRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/properties': typeof CustomerPropertiesRoute
  '/super-admin/admins': typeof SuperAdminAdminsRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/super-admin/system-reports': typeof SuperAdminSystemReportsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/super-admin': typeof SuperAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/agent/chat': typeof AgentChatRoute
  '/agent/customers': typeof AgentCustomersRoute
  '/agent/leads': typeof AgentLeadsRoute
  '/agent/login': typeof AgentLoginRoute
  '/agent/properties': typeof AgentPropertiesRoute
  '/agent/site-visits': typeof AgentSiteVisitsRoute
  '/customer/appointments': typeof CustomerAppointmentsRoute
  '/customer/chat': typeof CustomerChatRoute
  '/customer/enquiries': typeof CustomerEnquiriesRoute
  '/customer/favorites': typeof CustomerFavoritesRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/properties': typeof CustomerPropertiesRoute
  '/super-admin/admins': typeof SuperAdminAdminsRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/super-admin/system-reports': typeof SuperAdminSystemReportsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/super-admin/': typeof SuperAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/admin/agents'
    | '/admin/appointments'
    | '/admin/customers'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/properties'
    | '/admin/reports'
    | '/agent/chat'
    | '/agent/customers'
    | '/agent/leads'
    | '/agent/login'
    | '/agent/properties'
    | '/agent/site-visits'
    | '/customer/appointments'
    | '/customer/chat'
    | '/customer/enquiries'
    | '/customer/favorites'
    | '/customer/login'
    | '/customer/properties'
    | '/super-admin/admins'
    | '/super-admin/login'
    | '/super-admin/system-reports'
    | '/super-admin/users'
    | '/super-admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/admin/agents'
    | '/admin/appointments'
    | '/admin/customers'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/properties'
    | '/admin/reports'
    | '/agent/chat'
    | '/agent/customers'
    | '/agent/leads'
    | '/agent/login'
    | '/agent/properties'
    | '/agent/site-visits'
    | '/customer/appointments'
    | '/customer/chat'
    | '/customer/enquiries'
    | '/customer/favorites'
    | '/customer/login'
    | '/customer/properties'
    | '/super-admin/admins'
    | '/super-admin/login'
    | '/super-admin/system-reports'
    | '/super-admin/users'
    | '/super-admin'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/admin/agents'
    | '/admin/appointments'
    | '/admin/customers'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/properties'
    | '/admin/reports'
    | '/agent/chat'
    | '/agent/customers'
    | '/agent/leads'
    | '/agent/login'
    | '/agent/properties'
    | '/agent/site-visits'
    | '/customer/appointments'
    | '/customer/chat'
    | '/customer/enquiries'
    | '/customer/favorites'
    | '/customer/login'
    | '/customer/properties'
    | '/super-admin/admins'
    | '/super-admin/login'
    | '/super-admin/system-reports'
    | '/super-admin/users'
    | '/super-admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPropertiesRoute: typeof AdminPropertiesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AgentChatRoute: typeof AgentChatRoute
  AgentCustomersRoute: typeof AgentCustomersRoute
  AgentLeadsRoute: typeof AgentLeadsRoute
  AgentLoginRoute: typeof AgentLoginRoute
  AgentPropertiesRoute: typeof AgentPropertiesRoute
  AgentSiteVisitsRoute: typeof AgentSiteVisitsRoute
  CustomerAppointmentsRoute: typeof CustomerAppointmentsRoute
  CustomerChatRoute: typeof CustomerChatRoute
  CustomerEnquiriesRoute: typeof CustomerEnquiriesRoute
  CustomerFavoritesRoute: typeof CustomerFavoritesRoute
  CustomerLoginRoute: typeof CustomerLoginRoute
  CustomerPropertiesRoute: typeof CustomerPropertiesRoute
  SuperAdminAdminsRoute: typeof SuperAdminAdminsRoute
  SuperAdminLoginRoute: typeof SuperAdminLoginRoute
  SuperAdminSystemReportsRoute: typeof SuperAdminSystemReportsRoute
  SuperAdminUsersRoute: typeof SuperAdminUsersRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/admin/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/admin/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/properties': {
      id: '/admin/properties'
      path: '/admin/properties'
      fullPath: '/admin/properties'
      preLoaderRoute: typeof AdminPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/chat': {
      id: '/agent/chat'
      path: '/agent/chat'
      fullPath: '/agent/chat'
      preLoaderRoute: typeof AgentChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/customers': {
      id: '/agent/customers'
      path: '/agent/customers'
      fullPath: '/agent/customers'
      preLoaderRoute: typeof AgentCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/leads': {
      id: '/agent/leads'
      path: '/agent/leads'
      fullPath: '/agent/leads'
      preLoaderRoute: typeof AgentLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/login': {
      id: '/agent/login'
      path: '/agent/login'
      fullPath: '/agent/login'
      preLoaderRoute: typeof AgentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/properties': {
      id: '/agent/properties'
      path: '/agent/properties'
      fullPath: '/agent/properties'
      preLoaderRoute: typeof AgentPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/site-visits': {
      id: '/agent/site-visits'
      path: '/agent/site-visits'
      fullPath: '/agent/site-visits'
      preLoaderRoute: typeof AgentSiteVisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/appointments': {
      id: '/customer/appointments'
      path: '/customer/appointments'
      fullPath: '/customer/appointments'
      preLoaderRoute: typeof CustomerAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/chat': {
      id: '/customer/chat'
      path: '/customer/chat'
      fullPath: '/customer/chat'
      preLoaderRoute: typeof CustomerChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/enquiries': {
      id: '/customer/enquiries'
      path: '/customer/enquiries'
      fullPath: '/customer/enquiries'
      preLoaderRoute: typeof CustomerEnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/favorites': {
      id: '/customer/favorites'
      path: '/customer/favorites'
      fullPath: '/customer/favorites'
      preLoaderRoute: typeof CustomerFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/login': {
      id: '/customer/login'
      path: '/customer/login'
      fullPath: '/customer/login'
      preLoaderRoute: typeof CustomerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/properties': {
      id: '/customer/properties'
      path: '/customer/properties'
      fullPath: '/customer/properties'
      preLoaderRoute: typeof CustomerPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/super-admin'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/admins': {
      id: '/super-admin/admins'
      path: '/super-admin/admins'
      fullPath: '/super-admin/admins'
      preLoaderRoute: typeof SuperAdminAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/login': {
      id: '/super-admin/login'
      path: '/super-admin/login'
      fullPath: '/super-admin/login'
      preLoaderRoute: typeof SuperAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/system-reports': {
      id: '/super-admin/system-reports'
      path: '/super-admin/system-reports'
      fullPath: '/super-admin/system-reports'
      preLoaderRoute: typeof SuperAdminSystemReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/users': {
      id: '/super-admin/users'
      path: '/super-admin/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof SuperAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AdminAgentsRoute: AdminAgentsRoute,
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPropertiesRoute: AdminPropertiesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AgentChatRoute: AgentChatRoute,
  AgentCustomersRoute: AgentCustomersRoute,
  AgentLeadsRoute: AgentLeadsRoute,
  AgentLoginRoute: AgentLoginRoute,
  AgentPropertiesRoute: AgentPropertiesRoute,
  AgentSiteVisitsRoute: AgentSiteVisitsRoute,
  CustomerAppointmentsRoute: CustomerAppointmentsRoute,
  CustomerChatRoute: CustomerChatRoute,
  CustomerEnquiriesRoute: CustomerEnquiriesRoute,
  CustomerFavoritesRoute: CustomerFavoritesRoute,
  CustomerLoginRoute: CustomerLoginRoute,
  CustomerPropertiesRoute: CustomerPropertiesRoute,
  SuperAdminAdminsRoute: SuperAdminAdminsRoute,
  SuperAdminLoginRoute: SuperAdminLoginRoute,
  SuperAdminSystemReportsRoute: SuperAdminSystemReportsRoute,
  SuperAdminUsersRoute: SuperAdminUsersRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
